class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'megadl'
        self.UnzipMirrorCommand = 'munzipmirror'
        self.TarMirrorCommand = 'mtarmirror'
        self.CancelMirror = 'mcancel'
        self.CancelAllCommand = 'mcancelall'
        self.ListCommand = 'mlook'
        self.StatusCommand = 'mstatus'
        self.AuthorizeCommand = 'mauth'
        self.UnAuthorizeCommand = 'munauth'
        self.AuthListCommand = 'musers'
        self.PingCommand = 'mping'
        self.RestartCommand = 'mreboot'
        self.StatsCommand = 'mstats'
        self.HelpCommand = 'mhelp'
        self.LogCommand = 'mlog'
        self.SpeedCommand = 'mspeedtest'
        self.CloneCommand = 'mclone'
        self.WatchCommand = 'mwatch'
        self.TarWatchCommand = 'mtarwatch'
        self.DeleteCommand = 'mdx'
        self.UsageCommand = 'musage'
        self.RepoCommand = 'mrepo'

BotCommands = _BotCommands()
